# Generated by Django 4.2.2 on 2023-08-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0002_auto_20230709_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='comentario_demanda',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='region',
            field=models.CharField(blank=True, choices=[('amazonia', 'Amazonía'), ('orinoquia', 'Orinoquía'), ('pacifica', 'Pacífica')], max_length=100, null=True),
        ),
    ]
