# Generated by Django 4.2.2 on 2023-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0003_proceso_comentario_demanda_alter_proceso_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='Bioquimica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='Pot_requerida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='Termoquimica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='caso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='cub_bioq100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='cub_termo100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='punit1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='punit2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
