# Generated by Django 4.2.2 on 2023-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0004_proceso_bioquimica_proceso_pot_requerida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='punit1',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='punit2',
        ),
        migrations.AddField(
            model_name='proceso',
            name='Hibrida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='comentario_cubrimiento_planta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
