# Generated by Django 4.2.2 on 2023-09-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0005_remove_proceso_punit1_remove_proceso_punit2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='comentario_cantplantas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
