# Generated by Django 4.2.2 on 2023-09-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0007_proceso_pot_cgd_parcial_bioq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='cap',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
