# Generated by Django 4.2.2 on 2023-09-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0008_proceso_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='cap',
            field=models.TextField(),
        ),
    ]
