# Generated by Django 4.2.2 on 2023-09-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0009_alter_proceso_cap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='cap',
            new_name='cap_serializado',
        ),
    ]
