# Generated by Django 4.2.2 on 2023-09-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicación', '0011_proceso_cub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='cub_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
